services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
    volumes:
      - my-datavolume:/var/lib/mysql
  
  cinemas-api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_NAME=${DB_NAME}"
      - "DB_HOST=${DB_HOST}"     
    volumes:
      - "./api:/app"
    depends_on:
      - db
    links:
      - "db:database"

volumes:
  my-datavolume:
